services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    volumes:
      - /home/evgen/IdeaProjects/pastgresDataFromDockerContainer:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4:6.18
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=parom.evgen@mail.ru
#      #      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    restart: always